[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/notion/*"
  to = "/.netlify/functions/notion/:splat"
  status = 200
